### ISSUE TITLE
Fabric version not working?

### ISSUE THREAD

**Issue by OS-Void** [ExcessiveAmountsOfZombies/shop-visualizer#1]
To my understanding the same file has to be in the server and in the client, when I put it in the server it wouldn't start.

Error loading class: com/epherical/shopvisualizer/client/ShopVisualizerClient (java.lang.RuntimeException: Cannot load class com.epherical.shopvisualizer.client.ShopVisualizerClient in environment type SERVER)

But the client loads fine.

**Comment by ExcessiveAmountsOfZombies** [comment]
It's a client side mod only, if you're wanting to make use of the mod you would install Gunpowder Signshop, and then the shop-visualizer can read the data from the shop and display an item.

**Comment by OS-Void** [comment]
I got Signshop installed in the server, and the visualizer installed in the client but its not showing anything

Server ingame:
![2021-06-20_16 35 07](https://user-images.githubusercontent.com/5094754/122687636-0bd45180-d207-11eb-864d-06183a207639.png)

Client log:
Loading Mods
- shop-visualizer@${version}

Client shows it loaded, and no errors, but unable to see anything above shops.

**Comment by ExcessiveAmountsOfZombies** [comment]
which mc version and gunpowder signshop version?

**Comment by OS-Void** [comment]
MC: 1.17
Gunpowder Signshop: gunpowder-signshop-1.0.4+gunpowder.1.0.1.1.mc.1.17
Shop-Visualizer: shop-visualizer-fabric-1.0.1

**Comment by ExcessiveAmountsOfZombies** [comment]
ok, I took a look and gunpowder changed their NBT data, so I'll have to add a renderer for the updated format.

**Comment by ExcessiveAmountsOfZombies** [comment]
https://github.com/ExcessiveAmountsOfZombies/shop-visualizer/commit/9141e858a27ca1ee1c7b3b612698e2dca9291ef7 fixes it. I'll have it uploaded soon. also fixed the `shop-visualizer@${version}` so it should show the actual mod version now.
