### ISSUE TITLE
Signs are always shops

### ISSUE THREAD

**Issue by OS-Void** [ExcessiveAmountsOfZombies/shop-visualizer#2]
I made an issue a bit ago and fixed that issue but now blank signs that aren't supposed to be shops show as such:

![2021-06-22_23 05 06](https://user-images.githubusercontent.com/5094754/123029065-0d04aa80-d3d0-11eb-9679-c92ef4ad412b.png)

**Comment by ExcessiveAmountsOfZombies** [comment]
that's what i get for not paying attention. I even saw it create the shop is currently empty sign and thought nothing more of it.

**Comment by ExcessiveAmountsOfZombies** [comment]
Ok, uploading 1.0.3 right now and it fixes this. Thank you. Looking at it, it looks like gunpowders new NBT method would always apply their tag to the sign, even if it wasn't a shop, so my code was accepting that and just getting an empty tag, rather than a null tag.
